"""
Django settings for trunk_player project.

Generated by 'django-admin startproject' using Django 1.9.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import re
from urllib.parse import urlsplit

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/


def env_bool(name, default=False):
    """Read a true/false flag from the environment."""
    return os.getenv(name, str(default)).strip().lower() in ('true', '1', 't', 'yes', 'y', 'on')


def env_list(name, default=''):
    """Read a space or comma separated list from the environment."""
    return [item for item in re.split(r'[\s,]+', os.getenv(name, default)) if item]


# SECURITY WARNING: keep the secret key used in production secret!
# Set the SECRET_KEY environment variable (or override it in settings_local.py).
SECRET_KEY = os.environ.get("SECRET_KEY", '%2%xjx4c3obf_xa8hsdbd@ci+8!4)@x16_!auo*h(%*p_z(g')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG")

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "*")

# Django 4+ rejects HTTPS form posts (login, admin, ...) whose Origin is not
# listed here, e.g. "https://scanner.example.com"
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

LOGIN_URL = '/login/'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Application definition

INSTALLED_APPS = [
    # Must be first, makes "manage.py runserver" serve websockets too
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'local_override',
    'radio.apps.RadioConfig',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    #'allauth.socialaccount.providers.facebook',
    #'allauth.socialaccount.providers.instagram',
    'rest_framework',
    'channels',
    'django_select2',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'trunk_player.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trunk_player.wsgi.application'
ASGI_APPLICATION = "trunk_player.asgi.application"

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',
)

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = str(os.getenv("TZ", 'America/Los_Angeles'))

USE_I18N = True

USE_TZ = True

if env_bool("FORCE_SECURE"):
    # Honor the 'X-Forwarded-Proto' header for request.is_secure()
  SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

#STATICFILES_DIRS = [
#    os.path.join(BASE_DIR, "audio_files"),
#]

STATIC_ROOT = os.path.join(BASE_DIR, "static")

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50
}

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "audio_files")

# Redis is used to push live call notifications to browsers (channels)
# and for caching. Set REDIS_URL to point at your redis server.
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

# Channel settings
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        }
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # Use redis database 1 for the cache, channels uses the one in REDIS_URL
        "LOCATION": os.environ.get('REDIS_CACHE_URL', urlsplit(REDIS_URL)._replace(path='/1').geturl()),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# This Agency must exist in radio.Agency 
RADIO_DEFAULT_UNIT_AGENCY = 0

SITE_ID = 1

# Google sign in: create an OAuth client at https://console.cloud.google.com/
# with redirect URI https://<your site>/accounts/google/login/callback/
# and set GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", '')
GOOGLE_CLIENT_SECRET = os.environ.get("GOOGLE_CLIENT_SECRET", '')

SOCIALACCOUNT_PROVIDERS = \
    { 'google':
        { 'SCOPE': ['profile', 'email'],
          'AUTH_PARAMS': { 'access_type': 'online' } }}
if GOOGLE_CLIENT_ID:
    SOCIALACCOUNT_PROVIDERS['google']['APP'] = {'client_id': GOOGLE_CLIENT_ID, 'secret': GOOGLE_CLIENT_SECRET}

# Email, used for password resets and account emails. Without EMAIL_HOST
# emails are only printed to the log.
EMAIL_HOST = os.environ.get("EMAIL_HOST", '')
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", '587'))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", '')
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", '')
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)
if not EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Only ask people to confirm their email address when email can be sent
ACCOUNT_EMAIL_VERIFICATION = os.environ.get("ACCOUNT_EMAIL_VERIFICATION", 'optional' if EMAIL_HOST else 'none')

ACCOUNT_ADAPTER = 'radio.adapters.AccountAdapter'
SOCIALACCOUNT_ADAPTER = 'radio.adapters.SocialAccountAdapter'
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
LOGIN_REDIRECT_URL="/"

GOOGLE_ANALYTICS_PROPERTY_ID = os.environ.get("GOOGLE_ANALYTICS_PROPERTY_ID", '0')

SITE_TITLE = os.environ.get("SITE_TITLE", 'Trunk-Player')
SITE_EMAIL = os.environ.get("SITE_EMAIL", 'help@example.com')
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", SITE_EMAIL)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Set this to the location of your audio files. The default matches the
# /audio_files/ location served by the sample nginx configs, for S3 use
# something like '//s3.amazonaws.com/MY-BUCKET/'
AUDIO_URL_BASE = os.environ.get("AUDIO_URL_BASE", '/audio_files/')

# Which settings are passed into the javascript object js_config
JS_SETTINGS = ['SITE_TITLE', 'AUDIO_URL_BASE', 'STATIC_URL']

# Which settings are aviable to the template tag GET_SETTING
VISABLE_SETTINGS = ['SITE_TITLE', 'AUDIO_URL_BASE', 'GOOGLE_ANALYTICS_PROPERTY_ID', 'SITE_EMAIL', 'OPEN_SITE', 'ALLOW_GOOGLE_SIGNIN']

ALLOW_ANONYMOUS = env_bool("ALLOW_ANONYMOUS")

ACCESS_TG_RESTRICT = env_bool("ACCESS_TG_RESTRICT")

TALKGROUP_RECENT_LENGTH = int(os.getenv("TALKGROUP_RECENT_LENGTH", '15')) #  Minutes of history for TG recent_usage

ADD_TRANS_AUTH_TOKEN = os.environ.get("ADD_TRANS_AUTH_TOKEN", '7cf5857c61284') # Token to allow adding transmissions

OPEN_SITE = env_bool("OPEN_SITE") # If False new users cannot sign up
# Show the Google sign in button, on by default when GOOGLE_CLIENT_ID is set
ALLOW_GOOGLE_SIGNIN = env_bool("ALLOW_GOOGLE_SIGNIN", bool(GOOGLE_CLIENT_ID))
FIX_AUDIO_NAME = env_bool("FIX_AUDIO_NAME")
TRANS_DATETIME_FORMAT = os.environ.get("TRANS_DATETIME_FORMAT", '%H:%M:%S %m/%d/%Y')

USE_RAW_ID_FIELDS = env_bool("USE_RAW_ID_FIELDS")

# Load our local settings 
try:
    LOCAL_SETTINGS
except NameError:
    try:
        from trunk_player.settings_local import *
    except ImportError:
        pass
        # print("Failed to open settings_local.py")

