# Generated by Django 5.1.15 on 2026-09-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0062_siteoption_copyright_notice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="plan",
        ),
        migrations.RemoveField(
            model_name="stripeplanmatrix",
            name="radio_plan",
        ),
        migrations.DeleteModel(
            name="Plan",
        ),
        migrations.DeleteModel(
            name="StripePlanMatrix",
        ),
    ]
