# Generated by Django (data step added by hand) 5.1.15 on 2026-09-29 16:50

from django.db import migrations, models

from radio.slugs import is_candidate, slug_candidates


def dedupe_talkgroup_slugs(apps, schema_editor):
    """Give every talkgroup its own slug, the oldest keeps the plain one"""
    TalkGroup = apps.get_model('radio', 'TalkGroup')
    System = apps.get_model('radio', 'System')
    system_names = dict(System.objects.values_list('pk', 'name'))
    taken = set()
    for tg in TalkGroup.objects.order_by('pk').iterator():
        system_name = system_names.get(tg.system_id, '')
        slug = tg.slug
        if slug in taken or not is_candidate(slug, tg.alpha_tag, tg.dec_id, system_name):
            slug = next(c for c in slug_candidates(tg.alpha_tag, tg.dec_id, system_name) if c not in taken)
        taken.add(slug)
        if slug != tg.slug:
            TalkGroup.objects.filter(pk=tg.pk).update(slug=slug)


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0063_remove_payments_and_plans"),
    ]

    operations = [
        migrations.RunPython(dedupe_talkgroup_slugs, migrations.RunPython.noop),
    ]
