# Generated by Django 5.1.15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0064_dedupe_talkgroup_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="google_maps_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="talkgroup",
            name="slug",
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
