# Generated by Django 5.1.15 on 2026-10-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0065_unique_talkgroup_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkgroup',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='agency that uses this talkgroup', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talkgroups', to='radio.agency'),
        ),
        migrations.AddField(
            model_name='talkgroup',
            name='city',
            field=models.ForeignKey(blank=True, help_text='city or community this talkgroup covers, if it is local to one', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talkgroups', to='radio.city'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='short',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
