# Generated by Django 5.1.15 on 2026-09-29 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0065_unique_talkgroup_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="transmission",
            name="duplicate_of",
            field=models.ForeignKey(
                blank=True,
                help_text="the recording of the same call that is shown instead of this one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="duplicates",
                to="radio.transmission",
            ),
        ),
    ]
