# Generated by Django 5.1.15 on 2026-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0066_talkgroup_agency_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuscanlist',
            name='section',
            field=models.CharField(blank=True, help_text='heading this scan list is grouped under in the menu', max_length=30),
        ),
    ]
